import { EnemyConfig, Relic, TowerConfig, WeatherType } from '@/types/game';

export const TOWER_CONFIGS: Record<string, TowerConfig> = {
  ballista: {
    type: 'ballista',
    name: '弩炮哨塔 (Ballista Tower)',
    cost: { aether: 50, mana: 0 },
    description: '快速穿透单体射击。置于高台时射程与精度大幅提升，对飞行单位具克制效果。',
    range: 4.2,
    damage: 28,
    fireRate: 1.4,
    damageType: 'physical',
    color: '#8b5a2b',
    modelType: 'ballista',
    elevationBonusRange: 0.6,
    elevationBonusDmg: 5,
  },
  catapult: {
    type: 'catapult',
    name: '重型投石机 (Catapult)',
    cost: { aether: 80, mana: 15 },
    description: '远程抛射重石，对落点区域造成大范围重创与碎石冲击。',
    range: 6.0,
    damage: 65,
    fireRate: 0.45,
    damageType: 'earth',
    splashRadius: 2.2,
    color: '#654321',
    modelType: 'catapult',
    elevationBonusRange: 0.8,
    elevationBonusDmg: 12,
  },
  pyromancer: {
    type: 'pyromancer',
    name: '炼金炎塔 (Pyromancer Spire)',
    cost: { aether: 75, mana: 25 },
    description: '喷吐炙热烈焰，造成持续燃烧伤害。若将敌人引入低洼沟壑中，烈焰将点燃整个地缝！',
    range: 3.5,
    damage: 38,
    fireRate: 2.0,
    damageType: 'fire',
    burnDuration: 4.0,
    color: '#d34a26',
    modelType: 'pyromancer',
    elevationBonusRange: 0.4,
    elevationBonusDmg: 6,
  },
  arcane_prism: {
    type: 'arcane_prism',
    name: '奥术棱镜塔 (Arcane Prism)',
    cost: { aether: 110, mana: 50 },
    description: '汇聚地脉以太光束，对单一精英或首领目标造成持续增幅的高能贯穿伤害。',
    range: 4.8,
    damage: 75,
    fireRate: 1.8,
    damageType: 'energy',
    manaDrainPerShot: 3,
    color: '#7b3fd3',
    modelType: 'arcane_prism',
    elevationBonusRange: 0.7,
    elevationBonusDmg: 15,
  },
  cryo_obelisk: {
    type: 'cryo_obelisk',
    name: '冰封方尖碑 (Cryo Obelisk)',
    cost: { aether: 85, mana: 30 },
    description: '周期性释放冰晶寒霜，大幅减缓范围内魔物移速。若处于暴风雪天气，可直接冻结目标！',
    range: 3.8,
    damage: 22,
    fireRate: 0.8,
    damageType: 'frost',
    splashRadius: 3.2,
    slowPercent: 0.45,
    color: '#4db8ff',
    modelType: 'cryo_obelisk',
    elevationBonusRange: 0.5,
    elevationBonusDmg: 4,
  },
  geomancer: {
    type: 'geomancer',
    name: '地动战垒 (Geomancer Bastion)',
    cost: { aether: 95, mana: 35, sparks: 1 },
    description: '引发地脉震颤冲击波，击退周围步兵敌人，并对低洼地带敌人造成额外粉碎伤害。',
    range: 3.2,
    damage: 48,
    fireRate: 0.6,
    damageType: 'earth',
    splashRadius: 3.0,
    color: '#a07844',
    modelType: 'geomancer',
    elevationBonusRange: 0.3,
    elevationBonusDmg: 10,
  },
  mine: {
    type: 'mine',
    name: '地脉萃取机 (Leyline Extractor)',
    cost: { aether: 60, mana: 0 },
    description: '经济设施：每个波次产出 +35 晶石与 +20 灵脉能量。若建造在源石矿脉旁产量翻倍！',
    range: 1.5,
    damage: 0,
    fireRate: 0,
    damageType: 'physical',
    color: '#f0b830',
    modelType: 'mine',
    elevationBonusRange: 0,
    elevationBonusDmg: 0,
  },
  barricade: {
    type: 'barricade',
    name: '符文石垒 (Runed Barricade)',
    cost: { aether: 20, mana: 0 },
    description: '构筑坚不可摧的石垒以强制改变敌人的行进路线。拥有极高耐久度。',
    range: 0,
    damage: 0,
    fireRate: 0,
    damageType: 'physical',
    color: '#555555',
    modelType: 'barricade',
    elevationBonusRange: 0,
    elevationBonusDmg: 0,
  },
};

export const ENEMY_CONFIGS: Record<string, EnemyConfig> = {
  goblin: {
    type: 'goblin',
    name: '荒原掠夺者 (Wasteland Marauder)',
    maxHealth: 110,
    speed: 1.35,
    armor: 0,
    soulReward: 4,
    aetherReward: 12,
    isFlying: false,
    color: '#509e2f',
    size: 0.5,
    description: '敏捷的轻装小鬼，喜好成群结队沿最近路径狂奔。',
  },
  scout: {
    type: 'scout',
    name: '迅影潜行者 (Shadow Scout)',
    maxHealth: 80,
    speed: 2.1,
    armor: 0,
    soulReward: 5,
    aetherReward: 14,
    isFlying: false,
    color: '#b030b0',
    size: 0.45,
    description: '极速突击单位，若不及时减速很容易突破防线。',
  },
  armored_orc: {
    type: 'armored_orc',
    name: '重甲地窟蛮兵 (Armored Troll)',
    maxHealth: 380,
    speed: 0.75,
    armor: 0.35,
    soulReward: 12,
    aetherReward: 28,
    isFlying: false,
    color: '#8b4513',
    size: 0.85,
    description: '身负重型铁板，对物理弩炮有较强抗性，但惧怕炎塔与奥术。',
  },
  gargoyle: {
    type: 'gargoyle',
    name: '裂隙石像鬼 (Void Gargoyle)',
    maxHealth: 220,
    speed: 1.15,
    armor: 0.1,
    soulReward: 10,
    aetherReward: 22,
    isFlying: true,
    color: '#3d405b',
    size: 0.7,
    description: '飞行魔兽！无视地面任何地形高低与石垒阻隔，径直飞向地脉核心。',
    abilityDesc: '飞行单位：无视地面地形阻隔',
  },
  burrower: {
    type: 'burrower',
    name: '地脉遁地兽 (Leyline Burrower)',
    maxHealth: 290,
    speed: 1.05,
    armor: 0.2,
    soulReward: 14,
    aetherReward: 30,
    isFlying: false,
    color: '#c97a3e',
    size: 0.65,
    description: '可潜入低洼平地中隐蔽行进，但无法穿透高度>=2的高地！',
    abilityDesc: '撞击高地时被迫破土并陷入眩晕',
  },
  ash_elemental: {
    type: 'ash_elemental',
    name: '熔火余烬灵 (Ash Elemental)',
    maxHealth: 340,
    speed: 0.95,
    armor: 0.15,
    soulReward: 15,
    aetherReward: 32,
    isFlying: false,
    color: '#ff4500',
    size: 0.75,
    description: '由炽热地核诞生的元素体，免疫熔岩并缓慢自愈。',
  },
  colossus_boss: {
    type: 'colossus_boss',
    name: '天灾泰坦·撼地者 (Cataclysm Colossus)',
    maxHealth: 2600,
    speed: 0.55,
    armor: 0.45,
    soulReward: 120,
    aetherReward: 180,
    isFlying: false,
    color: '#402010',
    size: 1.6,
    description: '传说级巨兽！身躯重如泰山，每步迈出都会震颤大地。',
    abilityDesc: '极高生命与护甲，移动缓慢但具备强力冲撞',
  },
  storm_wyrm: {
    type: 'storm_wyrm',
    name: '天穹雷霆巨龙 (Tempest Wyrm)',
    maxHealth: 2100,
    speed: 1.0,
    armor: 0.25,
    soulReward: 150,
    aetherReward: 200,
    isFlying: true,
    color: '#2a52be',
    size: 1.8,
    description: '天际霸主！周身缠绕雷暴，直接跨越崇山峻岭直扑核心！',
    abilityDesc: '飞行首领：免疫冰冻，狂暴时移动速度提升',
  },
};

export const WEATHER_CONFIGS: Record<WeatherType, {
  name: string;
  desc: string;
  icon: string;
  color: string;
  ambientLight: number;
  fogColor: string;
  fogDensity: number;
}> = {
  clear: {
    name: '天清明朗 (Clear Sol)',
    desc: '万里无云，地脉灵能平稳。所有防御工事与魔物处于标准状态。',
    icon: '☀️',
    color: '#e6c86e',
    ambientLight: 1.0,
    fogColor: '#b0a08b',
    fogDensity: 0.008,
  },
  thunderstorm: {
    name: '雷暴交加 (Thunderstorm)',
    desc: '暴雨倾盆！水流地貌传导雷电伤害。飞行单位受气流紊乱减速 30%。',
    icon: '⛈️',
    color: '#5b84b1',
    ambientLight: 0.65,
    fogColor: '#3a4a58',
    fogDensity: 0.022,
  },
  ashfall: {
    name: '熔火落烬 (Volcanic Ashfall)',
    desc: '赤红火山灰弥漫。火系防御塔点燃范围 +40%，熔岩伤害翻倍！',
    icon: '🌋',
    color: '#d84a38',
    ambientLight: 0.75,
    fogColor: '#4d231b',
    fogDensity: 0.025,
  },
  blizzard: {
    name: '凛冬风雪 (Glacial Blizzard)',
    desc: '极寒暴风雪呼啸。所有地面魔物减速 25%，冰系方尖碑几率直接冻结！',
    icon: '❄️',
    color: '#80c5de',
    ambientLight: 0.85,
    fogColor: '#cfdbe6',
    fogDensity: 0.03,
  },
  miasma: {
    name: '深渊幽雾 (Abyssal Miasma)',
    desc: '幽暗迷雾笼罩战场。普通防御塔射程 -20%，但暴击伤害提升 60%！',
    icon: '🌫️',
    color: '#7a5a8c',
    ambientLight: 0.5,
    fogColor: '#2b1e33',
    fogDensity: 0.038,
  },
};

export const RELIC_POOL: Relic[] = [
  {
    id: 'apex_citadel',
    name: '崇高制高点 (Apex Citadel)',
    rarity: 'rare',
    icon: '⛰️',
    flavor: '“立于巍峨悬崖之上者，能看破千里狂澜。”',
    description: '处于高度 >= 3 的防御塔，攻击射程额外增加 +35%，暴击率提高 20%。',
    effect: (mods) => {
      mods.highGroundRangeBonus += 0.2;
      mods.highGroundDmgBonus += 0.15;
    },
  },
  {
    id: 'magma_infusion',
    name: '地心熔火注入 (Magma Infusion)',
    rarity: 'epic',
    icon: '🔥',
    flavor: '“将地幔深处的赤炎引导至护城深沟中。”',
    description: '被开凿至0层的深沟沟壑中，踏入的魔物承受额外 300% 灼烧伤害。',
    effect: (mods) => {
      mods.trenchBurnMult += 3.0;
    },
  },
  {
    id: 'tectonic_catalyst',
    name: '地脉共鸣水晶 (Tectonic Catalyst)',
    rarity: 'rare',
    icon: '💎',
    flavor: '“大地的骨骼在指尖随意折叠。”',
    description: '地形塑造成本（造物印记与原石）降低 40%，且每波开始时额外获得 +2 印记。',
    effect: (mods) => {
      mods.terraformingCostMult *= 0.6;
      mods.sparkYieldMult += 0.5;
    },
  },
  {
    id: 'storm_conductor',
    name: '引雷镀金盘 (Storm Conductor)',
    rarity: 'epic',
    icon: '⚡',
    flavor: '“引九霄奔雷，注入水脉沟渠之中。”',
    description: '雷暴天气下，水系或潮湿沟渠中魔物受到雷电连锁打击并眩晕 1.5 秒。',
    effect: (mods) => {
      mods.waterConductElectricity = true;
    },
  },
  {
    id: 'frost_shatter',
    name: '冰川碎裂咒 (Glacial Shatter)',
    rarity: 'rare',
    icon: '❄️',
    flavor: '“坚冰极脆，一击即碎。”',
    description: '暴风雪天气下或被冰冻的目标，承受额外 50% 物理与大地粉碎伤害。',
    effect: (mods) => {
      mods.blizzardShatterChance += 0.35;
    },
  },
  {
    id: 'soul_forge',
    name: '余烬吸魂炉 (Soul Extractor)',
    rarity: 'common',
    icon: '🔮',
    flavor: '“消逝的魔灵，化作古老遗迹的薪柴。”',
    description: '击杀魔物获得的余烬魂髓增加 50%。',
    effect: (mods) => {
      mods.soulYieldMult += 0.5;
    },
  },
  {
    id: 'geological_survey',
    name: '勘探秘术 (Geological Survey)',
    rarity: 'common',
    icon: '📜',
    flavor: '“深埋地下的矿脉无所遁形。”',
    description: '采矿萃取机产量提升 75%，击杀魔物获得的晶石增加 30%。',
    effect: (mods) => {
      mods.aetherYieldMult += 0.3;
    },
  },
  {
    id: 'uphill_quagmire',
    name: '泥泞陡坡 (Uphill Quagmire)',
    rarity: 'rare',
    icon: '🧗',
    flavor: '“让重甲敌人在仰攻中耗尽每一丝力气。”',
    description: '魔物在攀爬高度差 >= 1 的斜坡时，移动速度额外降低 45%。',
    effect: (mods) => {
      mods.enemiesSlowUphill += 0.35;
    },
  },
  {
    id: 'arcane_supercharge',
    name: '以太过载回路 (Aether Overcharge)',
    rarity: 'epic',
    icon: '✨',
    flavor: '“将灵脉魔能超载释放，灼穿泰坦甲胄。”',
    description: '奥术棱镜塔伤害提高 60%，但每次攻击额外消耗 1 点灵能。',
    effect: (mods) => {
      mods.towerDamageMult.arcane_prism += 0.6;
    },
  },
  {
    id: 'spiked_bastion',
    name: '荆棘花岗岩 (Spiked Granite)',
    rarity: 'rare',
    icon: '🛡️',
    flavor: '“即使是用血肉之躯去撞，也会被撞得粉身碎骨。”',
    description: '符文石垒与障碍墙壁反射受到的 100% 伤害，并提高 50% 耐久。',
    effect: (mods) => {
      mods.wallsReflectDamage = true;
    },
  },
  {
    id: 'weather_oracle',
    name: '观星者占天仪 (Weather Astrolabe)',
    rarity: 'legendary',
    icon: '🔭',
    flavor: '“顺天应时，借狂风暴雨以破千军。”',
    description: '使我方防御塔完全免疫天候带来的负面射程影响，并在极端天候中伤害 +30%。',
    effect: (mods) => {
      mods.weatherResistance = true;
    },
  },
  {
    id: 'trebuchet_cluster',
    name: '霰弹爆破重石 (Cluster Bombs)',
    rarity: 'epic',
    icon: '💣',
    flavor: '“重石落处，崩碎成千百枚灼热弹片。”',
    description: '投石机爆炸溅射半径增加 50%，并留下燃烧地面持续 3 秒。',
    effect: (mods) => {
      mods.towerRangeMult.catapult += 0.2;
      mods.towerDamageMult.catapult += 0.35;
    },
  },
  {
    id: 'ballista_piercing',
    name: '精钢穿云弩箭 (Piercing Bolts)',
    rarity: 'common',
    icon: '🏹',
    flavor: '“即使是天穹巨龙的双翼，也能一箭贯穿。”',
    description: '弩炮射速提高 35%，对飞行单位造成额外 80% 致命伤害。',
    effect: (mods) => {
      mods.towerDamageMult.ballista += 0.35;
    },
  },
  {
    id: 'prismatic_refraction',
    name: '折射水晶簇 (Prismatic Split)',
    rarity: 'legendary',
    icon: '💠',
    flavor: '“一道神光化万千，净化浊世妖氛。”',
    description: '奥术激光在命中目标后，会折射向附近额外 2 个敌人，造成 60% 溅射伤害。',
    effect: (mods) => {
      mods.towerDamageMult.arcane_prism += 0.4;
      mods.towerRangeMult.arcane_prism += 0.25;
    },
  },
];
